[Credentials]
# Paper trading endpoint: https://paper-api.alpaca.markets/v2
# Live trading endpoint:  https://api.alpaca.markets/v2
endpoint = "https://paper-api.alpaca.markets/v2"
key = "PKKLCGZ6R6S72GFS2ANTNR5VVV"
secret = "3qyvRvyUoXNEv3r1nWSFnWB3njKLEamkAQJm5YbpXCEa"
